### ISSUE TITLE
Leaking credentials into terraform state

### ISSUE THREAD

**Issue by max-frank** [QinetiQ-Cyber-Intelligence/OpenCTI-Terraform#1]
First of very nice deployment I am sure this will become a great starting point for people wanting to deploy their own instances.
I am aware the below describe issue is very nit picky, but this config is very well made and great contribution to the community so I want to help improve it even if its just a tiny thing.

When I went over your code I noticed that you are leaking credentials into terraform state in some places, most notably the opencti master password. Having the credentials in the terraform state introduces a few additional security risks e.g.,
- read permissions to the state file/bucket become will give access to all the secrets leaked into the state
- if used with a CI/CD pipeline anyone who can trigger a `terraform plan` is able to leak the secrets (see example below)

```terraform
data "http" "example" {
  url = "http://localhost:8888/${var.test}"
}

variable "test" {
 default = "foobar"
 sensitive = true
}
```

```bash
$ terraform plan

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no
differences, so no changes are needed.
```

```bash
$ python3 -m http.server 8888
Serving HTTP on :: port 8888 (http://[::]:8888/) ...
::1 - - [19/Aug/2022 08:50:19] code 404, message File not found
::1 - - [19/Aug/2022 08:50:19] "GET /foobar HTTP/1.1" 404 -
```
Since this is not supposed to be a production ready deployment this is not an issue per say, but it might be worth mentioning this in the documentation so that people less familiar with terraform will be aware and modify the code accordingly when preparing for a production configuration.

**Comment by ReadyElbow** [comment]
Hi @max-frank, 

I do see where you are coming from but I would say that this is **highly dependant** on the individuals CI/CD Pipeline solution.

The key thing is that if you are using a CI/CD Pipeline deployment, one would hope that the Terraform state file is put into a S3 Bucket with a S3 Bucket Policy restricting access with versioning enabled. I would not expect a local Terraform State file to be used as this firstly restricts collaboration and more importantly (as demonstrated) harms security.

As the `random` module is being used to generate passwords, this does help to protect the leaking of a password when `terraform plan/apply` is execute; Terraform will put in place `(sensitive)` without disclosing the generated password.

With a correctly setup CI/CD pipeline solution and locked down AWS Production account (to a few administrators with IAM Roles), the risk of stealing credentials from the Terraform state file is mitigated.

However, if an individual would like a more secure solution they could go about generating AWS Secret Manager Secrets outside of the Terraform deployment and reference these through Terraform resources. This would harm the automated deployment element and could introduce human error... Note that if the password were to be generated and then referenced by the deployment, I am unsure if this would even overcome the issue of credentials in the state file. Is a forced lookup possible for each `terraform plan/apply`?

If you are in agreement, I will mention some of this in the README.

**Comment by ReadyElbow** [comment]
Hi @max-frank,
I do see where you are coming from but I would say that this is highly dependant on the individuals CI/CD Pipeline solution.

The key thing is that if you are using a CI/CD Pipeline deployment, one would hope that the Terraform state file is put into a S3 Bucket with a S3 Bucket Policy restricting access with versioning enabled. I would not expect a local Terraform State file to be used as this firstly restricts collaboration and more importantly (as demonstrated) harms security. Regarding the addition of a new data source that requires the `http module`, this would require installation and should be subject to peer reviews in place on the CI/CD Pipeline and merge requests.

As the `random module` is being used to generate passwords, this does help to protect the leaking of a password when `terraform plan/apply` is executed; Terraform will put in place `(sensitive)` without disclosing the generated password.

With a correctly setup CI/CD pipeline solution and locked down AWS Production account (to a few administrators with IAM Roles), the risk of stealing credentials from the Terraform state file is mitigated.

However, if an individual would like a more secure solution they could go about generating AWS Secret Manager Secrets outside of the Terraform deployment and reference these through Terraform resources. This would harm the automated deployment element and could introduce human error... Note that if the password were to be generated and then referenced by the deployment, I am unsure if this would even overcome the issue of credentials in the state file. Is a forced lookup possible for each `terraform plan/apply`?

If you are in agreement, I will mention some of this in the README.

**Comment by max-frank** [comment]
I am in agreement that this is something everyone would have to check how it this impacts their CI/CD and security themselves (as you already mention in the readme). Though it would make it easier for others to make this assessment if you as you suggested mention this specific 'side effect' in the README.

HTTP module would in most configurations be unusual, but basically there are multiple ways to exfiltrate data at plan time. So having review+approval steps before CI/CD plan steps and not only apply steps is always important.

You are correct securest option would be to pre-generate all the passwords and only ever reference the secrets ARNs. Using a data source to load a secret version would end up in state.
